"""empty message

Revision ID: 8095f7eda324
Revises: c72d9df38aa8
Create Date: 2020-10-28 11:41:00.131007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8095f7eda324'
down_revision = 'c72d9df38aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Interests', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'Interests')
    # ### end Alembic commands ###
